//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int PersonID { get; set; }
        public string Person { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Password { get; set; }
    }
}
